// <auto-generated />
namespace Vezu_Vaziuoju.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AdminIdnotrequiredforpost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminIdnotrequiredforpost));
        
        string IMigrationMetadata.Id
        {
            get { return "202005051126597_AdminId not required for post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
